### ISSUE TITLE
cURL error 35

### ISSUE THREAD

**Issue by tokyomagic** [envato/wp-envato-market#104] opened 2017-05-08 11:29 UTC
Currently recieving the following error.

Download failed. cURL error 35: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

**Comment by JosKlever** [comment] 2017-05-08 11:40
This is not an issue of the Envato Market plugin, but your server is probably using an old version of cURL or OpenSSL. So you should contact your host to update the server.

**Comment by wpexplorer** [comment] 2017-05-12 21:43
@JosKlever I have a customer that is getting this error:

`cURL error 35: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure `

The customer contacted their hosting company and this was their response:

> This kind of error message is generated when a plugin and / or theme tries to connect to the remote server hosting the upgrade and fails. In this specific case, the secure transaction can not be completed because it uses the SSLv3 protocol, which is considered obsolete and unsafe for almost three years.

Is that correct?

Thanks!

**Comment by JosKlever** [comment] 2017-05-12 22:00
I'm not sure about the details, but I've found various posts via Google, where updating cURL and/or OpenSSL are mentioned as the solution,  So that sounds like it's solved (and caused) on server level.

**Comment by Cajs** [comment] 2017-05-15 08:47
@wpexplorer, @JosKlever's response was exactly correct. This is caused by a server having an outdated OpenSSL version on your server machine.

The only way it can be your plugin/theme's fault is if they use the --sslv3 argument to the curl command, which is highly unlikely, but you may wish to check.

A few useful commands to update openssl:
Debian / Ubuntu:
`sudo apt-get update; sudo apt-get upgrade`
CentOS: 
`yum -y install openssl`
Fedora:
`sudo yum -y install openssl`

**Comment by dtbaker** [comment] 2018-02-26 07:33
Hey all, we've changed edge providers so please let us know if any new SSL related issues appear. Closing now.

**Closed by dtbaker** 2018-02-26 07:33 UTC
Labels: bug
